<?php

namespace NfqAkademija\RecipeBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use NfqAkademija\RecipeBundle\Entity\Ingredient;

class LoadIngredientData extends AbstractFixture implements OrderedFixtureInterface
{
    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {

        $ingredients = [
            'Abrikosai',
            'Actas',
            'Adžika',
            'Agavos sirupas',
            'Agrastai',
            'Aguonos',
            'Agurkai',
            'Agurklė',
            'Agurotis',
            'Aitrieji pipirai',
            'Aitrioji paprika',
            'Ajerai',
            'Aliejus',
            'Alyvuogės',
            'Alyvuogių aliejus',
            'Alkoholis',
            'Alus',
            'Amaretas',
            'Anakardžių riešutai',
            'Ananasai',
            'Ančiuviai',
            'Anyžius',
            'Antiena',
            'Antienos krūtinėlė',
            'Antis',
            'Apelsinai',
            'Apelsino žievelė',
            'Apelsininiai pipirai',
            'Apelsinų likeris',
            'Apelsinų sultys',
            'Aperityvas',
            'Apyniai',
            'Arbata',
            'Arbūzai',
            'Argula',
            'Aronija',
            'Artišokai',
            'Asiūklis',
            'Aštuonkojis',
            'Augalinis aliejus',
            'Austrės',
            'Aviečių likeris',
            'Aviena',
            'Avietės',
            'Avižiniai dribsniai',
            'Avižos',
            'Avokadai',
            'Ąžuolas',
            'BACARDI BLACK',
            'BACARDI LIMON',
            'BACARDI OAKHEART',
            'BACARDI RAZZ',
            'BACARDI RESERVA',
            'BACARDI SUPERIOR',
            'Baklažanai',
            'Balanda',
            'Baltas vynas',
            'Baltieji pipirai',
            'Balzaminis actas',
            'Bambukų ūgliai',
            'Bananai',
            'Bandelės',
            'Baravykai',
            'Barštis sibirinis',
            'Basturma',
            'Batonas',
            'Bazilikai',
            'Bazilikas',
            'Bekonas',
            'Bertoletijų riešutai',
            'Biskvitiniai piršteliai',
            'Biteris',
            'Bobausiai',
            'Braškės',
            'Braškių sirupas',
            'Brendis',
            'Briediena',
            'Briuselio kopūstai',
            'Brokoliai',
            'Bruknės',
            'Builis',
            'Bulvės',
            'Bulvytės fri',
            'Burnotis',
            'Burokėliai',
            'Chalva',
            'Ciberžolė',
            'Cikorija',
            'Cinamonas',
            'Citrininiai pipirai',
            'Citrinos',
            'Citrinos rūgštis',
            'Citrinos žievelė',
            'Citrinų džemas',
            'Citrinų sultys',
            'Citrinžolė',
            'Coca Cola',
            'Cukatos',
            'Cuki',
            'Cukinija',
            'Cukraus pudra',
            'Cukraus sirupas',
            'Cukrus',
            'Churma',
            'Čederio sūris',
            'Čes',
            'Česnakas',
            'Čili pipiras',
            'Čiobreli',
            'Čiobreliai',
            'Čiužutės',
            'Daktariška dešra',
            'Daržovės',
            'Daši',
            'Dašiai',
            'Datulės',
            'Degtinė',
            'Dešra',
            'Dešrelės',
            'Detinė',
            'Dilgėlės',
            'Dižono garstyčios',
            'Druksa',
            'Druska',
            'Dumplainiai',
            'Dumplūnė',
            'Duona',
            'Duonmedis',
            'Duonos trupiniai',
            'Džemas',
            'Džinas',
            'Džiūvėsėliai',
            'Ėriena',
            'Eršketas',
            'Erškėtis erškėtrožė',
            'Ešerys',
            'Faršas',
            'Fazanas',
            'Feichoja',
            'Figos',
            'Garstyčios',
            'Garstyčių milteliai',
            'Garšva',
            'Gazuotas vanduo',
            'Geldelės',
            'Gelsvė',
            'Gelteklės',
            'Gervuogės',
            'Gira',
            'Girtuoklės',
            'Gyslotis',
            'Gluosnis',
            'Graikiniai riešutai',
            'Granatai',
            'Granatų sultys',
            'Gražgarstės',
            'Greipfrutai',
            'Grybai',
            'Grietinė',
            'Grietinėlė',
            'Griežčiai',
            'Grikiai',
            'Grūdai',
            'Grūzdai',
            'Gudobelė',
            'Guminukai',
            'Gvazdikėliai',
            'Ieva',
            'Ikrai',
            'Imbieras',
            'Imbierinis alus',
            'Imbierinis alus "Ginger Beer"',
            'Imbierinis limonadas',
            'Imbierinis limonadas "Ginger Ale"',
            'Irisai',
            'Išrūgos',
            'Jalapenai',
            'Japoniškas pipiras',
            'Jaučio inkstai',
            'Jaučio kepenys',
            'Jaučio liežuvis',
            'Jaučio plaučiai',
            'Jautiena',
            'Jautienos faršas',
            'Jogurtas',
            'Jogurto bakterijos raugas',
            'Jonažolė',
            'Judra',
            'Juodieji pipirai',
            'Juodieji serbentai',
            'Juodųjų serbentų sultys',
            'Juozažolė',
            'Jūros dumblių lapai Nori',
            'Jūros gėrybės',
            'Jūros kopūstai',
            'Jūros lydeka',
            'Kadagio uogos',
            'Kajeno pipiras',
            'Kakava',
            'Kalakutiena',
            'Kalendra',
            'Kaliaropės',
            'Kalmarai',
            'Kalpokai',
            'Kalvadosas',
            'Kamut kruopos',
            'Kanapės',
            'Kaparėliai',
            'Kaparis',
            'Karamelė',
            'Kardamonas',
            'Karis',
            'Karosai',
            'Karpis',
            'Karšis',
            'Katuogės',
            'Kava',
            'Kazlėkai',
            'Kečupas',
            'Ked',
            'Kedro riešutai',
            'Kefyras',
            'Kelmučiai',
            'Kepenėlės',
            'Kepimo milteliai',
            'Kepimo soda',
            'Kiaulės ausys',
            'Kiaulės galva',
            'Kiaulės inkstai',
            'Kiaulės kepenys',
            'Kiaulės kojos',
            'Kiaulės kumpis',
            'Kiaulės liežuvis',
            'Kiaulės smegenys',
            'Kiaulės širdis',
            'Kiauliena',
            'Kiaulienos faršas',
            'Kiaulienos lašiniai',
            'Kiaulienos nugarinė',
            'Kiaulienos sprandinė',
            'Kiaulienos šoninė',
            'Kiaulių žarnos',
            'Kiaulpienė',
            'Kiaušiniai',
            'Kietasis sūris',
            'Kininis finikas',
            'Kininis kopūstas',
            'Kiniškasis arbatmedis',
            'Kinkanai',
            'Kiselius',
            'Kisielius',
            'Kiškiena',
            'Kiškio kopūstai',
            'Kiviai',
            'Klevas',
            'Klevų sirupas',
            'Kmynai',
            'Knorr FIX mišinys spagečiams „Carbonara“',
            'Knorr Fix ruošinys Arrabiata',
            'Knorr FIX ruošinys spagečiams „Bolognese“',
            'Knorr FIX ruošinys spagečiams su 4 sūrių ir brokolių padažu',
            'Kokosas',
            'Kokoso drožlės',
            'Kokosų pienas',
            'Kola',
            'Kola gėrimas',
            'Kolamedis',
            'Koliurija',
            'Kondensuotas pienas',
            'Konjakas',
            'Konservai',
            'Konservuoti kukurūzai',
            'Konservuoti žirneliai',
            'Kopūstai',
            'Krabai',
            'Krabų lazdelės',
            'Krakmolas',
            'Krakmolo sirupas',
            'Krapai',
            'Kraujažolė',
            'Krekeriai',
            'Kremas',
            'Krevetės',
            'Krevetės be kevalo',
            'Kriaušės',
            'Kriaušiai',
            'Krienai',
            'Kukurūzai',
            'Kukurūzų dribsniai',
            'Kukurūzų kruopos',
            'Kumpis',
            'Kuoja',
            'Kurapka',
            'Kuskusas',
            'Kvapieji pipirai',
            'Kviečiai',
            'Kvietiniai miltai',
            'Laimai',
            'Laimas',
            'Laimo sultys',
            'Laiškiniai česnakai',
            'Lakštiniai makaronai',
            'Langustas',
            'Lašiša',
            'Lauro lapai',
            'Lavašas',
            'Lazanija',
            'Lazdyno riešutai',
            'Ledai',
            'Ledukai',
            'Lęšiai',
            'Levandos',
            'Lydeka',
            'Lydytas sūris',
            'Liepžiedžiai',
            'Likeris',
            'Likeris "POÉMA Creme"',
            'Limonadas',
            'Lynas',
            'Linų sėmenys',
            'Litis',
            'Lūgnė',
            'Mairūnas',
            'Majonezas',
            'Makadamijų riešutai',
            'Makaronai',
            'Makavykai',
            'Mandarinai',
            'Mango',
            'Mangoldai',
            'Manų kruopos',
            'Margarinas',
            'Marinatas acto',
            'Marinuoti agurkai',
            'Marmeladas',
            'MARTINI BIANCO',
            'Martini Bitter',
            'MARTINI EXTRA DRY',
            'Martini Prosecco',
            'MARTINI ROSATO',
            'MARTINI ROSSO',
            'Mascarpone sūris',
            'Medlieva',
            'Medus',
            'Melasa',
            'Mėlynės',
            'Melionai',
            'Melisa',
            'Menkės',
            'Mėsa',
            'Mėta',
            'Midijos',
            'Midus',
            'Mielės',
            'Miežiai',
            'Miežinės kruopos',
            'Migdolai',
            'Miltai',
            'Mineralinis vanduo',
            'Mirinas',
            'Mišinys picai',
            'Mocarela sūris',
            'Moliūgai',
            'Moliūgas',
            'Moliūgų sėklos',
            'Morkos',
            'Morkų sultys',
            'Muskatas',
            'Nakviša',
            'Napaleono lakštai',
            'Nendrė',
            'Nitrinė druska salietra',
            'Notra',
            'Nuoviras',
            'Obelių aliejus',
            'Obuolaia',
            'Obuoliai',
            'Obuolių actas',
            'Obuolių sultys',
            'Okra',
            'Ožkos pieno sūris',
            'Pabarstukai',
            'Paberžiai Lepšiai',
            'Padažas',
            'Panevėžio cukrus plius',
            'Pankoliai',
            'Pankolis',
            'Papaja',
            'Papartis',
            'Paprika',
            'Paprikos milteliai',
            'Parmezano sūris',
            'Paršelis',
            'Pastarnokas',
            'Pasukos',
            'Paštetas',
            'Patisonai',
            'Paukštiena',
            'Pekano riešutai',
            'Pekino kopūstai',
            'Pelerūnas kietis',
            'Pelėsinis sūris',
            'Perlinės kruopos',
            'Persikai',
            'Persimonas Churma',
            'Peru pipiras',
            'Petražolės',
            'Piena',
            'Pienas',
            'Pienės',
            'Pievagrybiai',
            'Pikulė',
            'Piliarožė',
            'Pipirai',
            'Pipirmėtė',
            'Pipirnė',
            'Pistacijos',
            'Pita',
            'Plekšnė',
            'Plūdena',
            'Pomidorai',
            'Pomidorų padažas',
            'Pomidorų pasta',
            'Pomidorų sultys',
            'Poras',
            'Portulaka',
            'Prancūziški rageliai',
            'Prieksoniai',
            'Prieskoniai',
            'Prieskoninės žolelės',
            'Provanso žolelės',
            'Pudingas',
            'Pūgžlys',
            'Punšas',
            'Pupelės',
            'Pupos',
            'Pušis',
            'Putinas',
            'Putojantis vynas',
            'Putpelė',
            'Putpelės kiaušiniai',
            'Rabarbarai',
            'Raktažolė',
            'Ramunės',
            'Rapsų aliejus',
            'Raskila',
            'Raudonas vynas',
            'Raudonėliai Oreganas',
            'Raudonieji serbentai',
            'Raudonikiai',
            'Raudonųjų ir baltųjų serbentų sultys',
            'Raugerškis',
            'Rauginti agurkai',
            'Rauginti kopūstai',
            'Razinos',
            'Ridikai',
            'Ridikėliai',
            'Riebalai',
            'Riešutai',
            'Rislingas',
            'Ryžiai',
            'Ryžių makaronai',
            'Romas',
            'Romas "Captain Morgan"',
            'Ropės',
            'Rozmarinas',
            'Rožiniai pipirai',
            'Rudmėsės',
            'Rugiagėlės',
            'Rugiai',
            'Ruginiai miltai',
            'Rūgpienis',
            'Rūgštynės',
            'Runkeliai',
            'Rūtos',
            'Saida',
            'Sakė',
            'Saldainiai',
            'Saldymedis',
            'Saliamis',
            'Salierai',
            'Salieras',
            'Salyklas',
            'Salotos',
            'SANTA MARIA juodieji pipirai',
            'SANTA MARIA juodųjų pipirų',
            'SANTA MARIA aitriosios paprikos',
            'SANTA MARIA aitriųjų paprikų',
            'SANTA MARIA akmens druska',
            'SANTA MARIA akmens druskos',
            'SANTA MARIA akmens druskos, malūnėlyje',
            'SANTA MARIA ANCHO ST YLE aitriosios paprikos',
            'SANTA MARIA cinamonas',
            'SANTA MARIA cinamono lazdelės',
            'SANTA MARIA CHIPOTLE aitriosios paprikos',
            'SANTA MARIA CHIPOTLE aitriųjų paprikų',
            'SANTA MARIA druska',
            'SANTA MARIA gvazdikėliai',
            'SANTA MARIA JALAPENO aitriosios paprikos',
            'SANTA MARIA kmynų',
            'SANTA MARIA lauro lapai',
            'SANTA MARIA malto cinamono',
            'SANTA MARIA maltų paprikų',
            'SANTA MARIA NACHO kukurūzų traškučių',
            'Santa Maria prieskoniai "Kakava ir aitrioji paprika"',
            'SANTA MARIA raudonėliai',
            'SANTA MARIA RED HOT aitriosios paprikos',
            'SANTA MARIA RED HOT aitriosios paprikos dribsniai',
            'SANTA MARIA RED HOT aitriųjų paprikų dribsnių',
            'SANTA MARIA saulėje džiovintų pomidorų',
            'SANTA MARIA TACO padažo',
            'SANTA MARIA TELLICHERRY pipirų',
            'SANTA MARIA TEX MEX tortilijos',
            'SANTA MARIA TEX MEX tortilijų',
            'SANTA MARIA vanilinis cukrus',
            'Sardinės',
            'Saulėgrąžos',
            'Saulėgrąžų aliejus',
            'Sausainiai',
            'Sausmedis',
            'Sedula',
            'Sėklų mišinys',
            'Sėlenos',
            'Seliava',
            'Seza',
            'Sezamas',
            'Sezamų aliejus',
            'Sičuano pipiras',
            'Sidabražolė',
            'Sidras',
            'Silkė',
            'Sirupas',
            'SKANULIO kiaulienos sprandinės armėniškas šašlykas',
            'Skumbrė',
            'Slyvos',
            'Smidras',
            'Soda',
            'Soja',
            'Sojos',
            'Sojos padažas',
            'Sorų kruopos',
            'Spageti',
            'Spanguolės',
            'Spiritas',
            'Sprite',
            'Sraigės vynuoginės',
            'Starkis',
            'Stinta',
            'Stirniena',
            'Sula',
            'Sultinys',
            'Sultys',
            'Sūrelis',
            'Sūris',
            'Sutirštintas pienas',
            'Sutys',
            'Svarainiai',
            'Sviestas',
            'Sviesto skonio „Rama Maestro“',
            'Svietsas',
            'Svogūnai',
            'Svogūnų laiškai',
            'Šafranas',
            'Šalavijas',
            'Šalpusnis',
            'Šaltalankis',
            'Šaltekšnis',
            'Šamas',
            'Šermukšnis',
            'Šerniena',
            'Šiitake grybai',
            'Šilauogės',
            'Šokoladas',
            'Šokoladas, juodasis',
            'Šokoladas, pieniškas',
            'Šparagai',
            'Šparaginės pupelės',
            'Špinatai',
            'Šprotai',
            'Švendras',
            'Tabasko padažas',
            'Taukai kiaulių',
            'Tekila',
            'Tekšė',
            'Tešla',
            'Tetervinas',
            'Tilapija',
            'Tyrė',
            'Tofu - sojų varškė',
            'Tonikas',
            'Topinambai',
            'Tortilija',
            'Trauktinė',
            'Trešnės',
            'Triušiena',
            'Tunas',
            'Ūmedės',
            'Ungurys',
            'Uogienė',
            'Uogos',
            'Upėtakis',
            'Vafliai',
            'Vaisiai',
            'Vaistinė ožragė',
            'Valgomieji dažai',
            'Vanduo',
            'Vanilė',
            'Vanilės lazdelės',
            'Vanilinas',
            'Vanilinė',
            'Vanilinis cukrus',
            'Varlių šlaunelės',
            'Varnalėša',
            'Varškė',
            'Varškės sūris',
            'Vasabi',
            'Vėgėlė',
            'Vermutas',
            'Veršiena',
            'Veršienos faršas',
            'Vėžiai',
            'Vijūnai',
            'Vynas',
            'Vyno actas',
            'Vynuogės',
            'Vynuogių sultys',
            'Virtos MAŽYLIŲ dešrelės',
            'Virtos MAŽYLIŲ dešrelės Šeimos pakuotė',
            'Virtos MAŽYLIŲ dešrelės su kalakutiena',
            'Virtos MAŽYLIŲ dešrelės su sūriu',
            'Viskis',
            'Vyšnios',
            'Vištiena',
            'Vištienos faršas',
            'Vištienos filė',
            'Vištų blauzdelės',
            'Vištų kakleliai',
            'Vištų kepenėlės',
            'Vištų skrandukai',
            'Vištų sparneliai',
            'Vištų širdelės',
            'Vorčesterio padažas',
            'Voveraitės',
            'Zefyrai',
            'Žalioji citrina',
            'Žaliosios citrinos sultys',
            'Žaliuokės',
            'Žalumynai',
            'Žalumynai įvairūs',
            'Žąsis',
            'Želatina',
            'Želė',
            'Želės cukrus „Multi“',
            'Žemės riešutai',
            'Žemės riešutų aliejus',
            'Žemuogės',
            'Ženšenis',
            'Ženuogės',
            'Žiediniai kopūstai',
            'Žirneliai',
            'Žirniai',
            'Žuvies piršteliai',
            'Žuvis'
        ];

        foreach($ingredients as $ingredient){
            $data = new Ingredient();
            $data->setName($ingredient);
            $manager->persist($data);
        }
        $manager->flush();

    }

    /**
     * {@inheritDoc}
     */
    function getOrder()
    {
        return 1;
    }
}
