<?php

namespace NfqAkademija\RecipeBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;


/**
 * IngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRepository extends EntityRepository
{
    /**
     * @param string $term
     * @return array
     */
    public function getFiltered($term)
    {
        $em = $this->getEntityManager();
        $ingredients = $em
            ->createQuery(
                'SELECT i
                 FROM RecipeBundle:Ingredient i
                 WHERE i.name LIKE :searchterm
                 ORDER BY i.id ASC'
            )
            ->setParameter('searchterm', '%'.$term.'%')
            ->getResult();

        return $ingredients;
    }
}
