<?php

namespace NfqAkademija\RecipeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecipeIngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeIngredientRepository extends EntityRepository
{
}
