<?php

namespace NfqAkademija\RecipeBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * RecipeIngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeIngredientRepository extends EntityRepository
{
    public function getOrderedRecipes($ingredients)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            "
                            SELECT r, COUNT(i.id)/SIZE(r.ingredients) koef
                            FROM RecipeBundle:Recipe r
                            LEFT JOIN r.ingredients ri
                            LEFT JOIN ri.ingredient i
                            WHERE i.name IN (:ing)
                            GROUP BY r
                            ORDER BY koef DESC


                        "
        )->setParameter('ing', $ingredients);

        $goodRecipes = $query->getResult();

        $query = $em->createQuery(
            "
                            SELECT r, 0 koef
                            FROM RecipeBundle:Recipe r
                            LEFT OUTER JOIN r.ingredients ri
                            INNER JOIN ri.ingredient i
                            WHERE i.name NOT IN (:ing)

                        "
        )->setParameter('ing', $ingredients);

        $otherRecipes = $query->getResult();

        $recipes = array_merge($goodRecipes, $otherRecipes);

        return $recipes;

    }
}
