<?php

namespace NfqAkademija\RecipeBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends EntityRepository
{
    public function getByIngredients($ingredientIds, $offset = 0, $limit = 0)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("

            SELECT r recipe, rr, rv, rimg,  COUNT(DISTINCT ri.id)/SIZE(r.ingredients) koef, SIZE(r.ingredients)-COUNT(DISTINCT ri.id) missing
            FROM RecipeBundle:Recipe r
            LEFT JOIN r.ingredients ri
                WITH ri.ingredient IN (:ids)
            LEFT JOIN r.recipeRating rr
            LEFT JOIN r.votes rv
            LEFT JOIN r.images rimg
            GROUP BY r.id
            ORDER BY missing ASC

        ")
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->setParameter('ids', $ingredientIds);

        return $query->getResult();
    }
}
