<?php

namespace NfqAkademija\RecipeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VotesRepository extends EntityRepository
{
    public function hasUserVoted($id, $ip)
    {
        $sql = 'SELECT r.id, v.ip
        FROM votes v RIGHT JOIN recipes r
        ON v.recipe_id = r.id WHERE r.id = ? AND v.ip = ?';
        
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute([$id, $ip]);

        // User has already voted or recipe with such id has not been found.
        if($stmt->rowCount() > 0){
            return true;
        }

        return false;
    }
}
